name: CI

on:
  push:
    branches: [develop, release]
  pull_request:
    branches: [develop, release]

jobs:
  ci:
    name: Continuous Integration
    permissions:
      contents: read
    timeout-minutes: 15
    strategy:
      matrix:
        os: ["ubuntu-22.04", "windows-latest"]  # Remove MacOS (billing + github.com/ThalesGroup/scio/issues/2)
        python-version: ["3.12", "3.13"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Collect Workflow Telemetry
        uses: TheoGoudout/workflow-telemetry-action@32fae7f474780a2e1ce0e33ac68f243d00ccc57e
        with:
          save_raw_stats: true

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Install uv and set python version
        uses: astral-sh/setup-uv@f94f6a7064372557457491745799754701235339
        with:
          version: "0.8.17"
          python-version: ${{ matrix.python-version }}
          enable-cache: true

      - name: Run ruff
        run: |
          uvx -v ruff check
          uvx -v ruff format --diff

      - name: Run mypy
        run: |
          uv -v run mypy

      - name: Build & Install
        run: |
          uv -v build
          uv -v pip install dist/scio_pypi-1.0.1.dev0-py3-none-any.whl

      - name: Build docs (Posix)
        if: matrix.os != 'windows-latest'
        env:
          SPHINXOPTS: --fail-on-warning
        run: |
          uv -v run make -C docs

      - name: Build docs (Windows)
        if: matrix.os == 'windows-latest'
        env:
          SPHINXOPTS: --fail-on-warning
        run: |
          uv -v run cmd /c "docs\\make.bat"

      - name: Run pytest
        id: run-pytest
        continue-on-error: true
        run: |
          uv -v run pytest -vv --cov-report=xml

      - name: Upload observed plots on failure
        if: ${{ steps.run-pytest.outcome == 'failure' }}
        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08
        with:
          name: pytest-observed-${{ matrix.os }}-py${{ matrix.python-version }}
          path: test/expected/*/*.observed.*
          retention-days: 30

      - name: Fail the job if pytest failed
        if: ${{ steps.run-pytest.outcome == 'failure' }}
        run: exit 1

      - name: Upload coverage report to Codecov
        if: matrix.os == 'ubuntu-22.04' && matrix.python-version == '3.13'
        uses: codecov/codecov-action@0565863a36f2c73235651478553241285215034c
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true

      # TEMPORARILY DISABLED (https://github.com/ThalesGroup/scio/issues/9)
      # - name: Run pytest with lowest resolution
      #   id: run-pytest-lowest
      #   continue-on-error: true
      #   run: |
      #     uv -v run --refresh --resolution=lowest pytest -vv

      # - name: Upload observed plots on lowest failure
      #   if: ${{ steps.run-pytest-lowest.outcome == 'failure' }}
      #   uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08
      #   with:
      #     name: pytest-lowest-observed-${{ matrix.os }}-py${{ matrix.python-version }}
      #     path: test/expected/*/*.observed.*
      #     retention-days: 7

      # - name: Fail the job if pytest lowest failed
      #   if: ${{ steps.run-pytest-lowest.outcome == 'failure' }}
      #   run: exit 1
